### ISSUE TITLE
pass user/password to mosquito-broker

### ISSUE THREAD

**Issue by martin-perlinger** [dwyschka/hsp-mqtt-bridge#3]
hello dwyschka!

i was able to install hsp-mqtt-bridge successfully.
i adapted the docker-compose.yml to my environment
i am using 'mosquitto broker' addon on my homeassistant. how can user/password be passed to the homeassistant moquitto-broker?

mqtt-log:
2024-01-25 14:16:23: Client hsp_pellet_stove disconnected, not authorised.

thank you.

Martin

**Comment by dwyschka** [comment]
i would add it in the evening :) 

i dont use authorization on my setup

**Comment by martin-perlinger** [comment]
wow! that's fast...
... and very nice!

:-)

**Comment by dwyschka** [comment]
> wow! that's fast... ... and very nice!
> 
> :-)

I've updated the container. 

Please add following to your environment variables: 

````
MQTT_USE_AUTH=true;
MQTT_USER=rwYourUsername
MQTT_PASSWORD=YourPass
````

**Comment by martin-perlinger** [comment]
works fine - thank you!
